apiVersion: v1
kind: ReplicationController
metadata:
  name: docker-web-app-rc
spec:
  replicas: 1
  selector:
    app: docker-web-app
  template:
    metadata:
      name: docker-web-app
      labels:
        app: docker-web-app
    spec:
      containers:
      - name: docker-web-app-container
        image: vanderk/docker_web_app:v01
        ports:
        - containerPort: 8080